# Question 1
PS C:\Users\User> cd C:\infosys\IEM4723_Fall2026_Assignments\assignment1\regression_container
docker build -t linear-regression-app .
docker tag linear-regression-app elysesardega/linear-regression-app:v0.1.1
docker tag linear-regression-app elysesardega/linear-regression-app:v0.1.2
docker tag linear-regression-app elysesardegna/linear-regression-app:latest #made a mistake in tagging
docker push linear-regression-app elysesardegna/linear-regression-app:latest

# Question 2
